# -*- coding: utf-8 -*-
"""gen_jpn_text.py - generate the C++ side of the Japanese text support.

Writes three files from tools/jpn_font_table.py and the JPN executable:

  src/game/JpnFontTable.h    codepoint -> FONT.TIM glyph bytes, sorted, the
                             lookup table STR_JP() searches at compile time
  src/game/JpnTextTables.cpp the four Japanese text tables held in
                             Biohazard.exe: global messages, item names,
                             unexamined-item names and item descriptions
  tools/test_str_jp.cpp      static_asserts every one of those strings against
                             the bytes in the executable

The two generated sources are written with a UTF-8 BOM: they are full of u8""
literals and MSVC only reads those as UTF-8 when the source declares itself so.

  python tools/gen_jpn_text.py
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from jpn_font_table import build_map  # noqa: E402
import jpn_msg_decode as msg  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SELF = 'tools/gen_jpn_text.py'

HEADER_TOP = '''\
// JpnFontTable.h - GENERATED by %s, do not edit by hand.
//
// Unicode -> Japanese FONT.TIM glyph bytes, sorted by codepoint so STR_JP()
// can binary-search it in a constant expression. `n` is how many of b0/b1 the
// glyph uses; a two-byte glyph's b0 is 0xF8 (left page rows 13-15), 0xF9
// (right page rows 0-13) or 0xFA (right page rows 14-17). The layout those
// encode is documented in docs/TEXT_ENCODING.md and tools/jpn_font_table.py.
//
// `n` is carried explicitly rather than inferred from `b1 == 0`, because a
// second byte of zero is legal and common: it is column 0 of a row, so U+58CA
// is the two bytes F9 00 and U+4E45 is FA 00.
#pragma once

namespace pft_detail {

struct JpnGlyph {
    unsigned short cp;
    unsigned char  n;
    unsigned char  b0;
    unsigned char  b1;
};

constexpr JpnGlyph kJpnGlyphs[] = {
''' % SELF

HEADER_BOTTOM = '''};

constexpr int kJpnGlyphCount = (int)(sizeof(kJpnGlyphs) / sizeof(kJpnGlyphs[0]));

// Binary search; returns the index of `cp` or -1. Constant-expression usable.
constexpr int jpnGlyphIndex(unsigned int cp)
{
    int lo = 0;
    int hi = kJpnGlyphCount - 1;
    while (lo <= hi) {
        int mid = (lo + hi) / 2;
        if (kJpnGlyphs[mid].cp < cp) {
            lo = mid + 1;
        } else if (kJpnGlyphs[mid].cp > cp) {
            hi = mid - 1;
        } else {
            return mid;
        }
    }
    return -1;
}

} // namespace pft_detail
'''

CPP_TOP = '''\
// JpnTextTables.cpp - GENERATED by %s, do not edit by hand.
//
// Every text table the Japanese PC release (Biohazard.exe) holds in its own
// executable, decoded and written back as readable Japanese. STR_JP() encodes
// each string to FONT.TIM glyph bytes at compile time, and every entry here
// re-encodes to the exact bytes the original holds - checked two ways, by
// `python tools/jpn_msg_decode.py verify` and by the static_asserts in
// tools/test_str_jp.cpp.
//
//   global_messages_jpn          0x004CDE58  set_message_display 0x00491980
//   g_ItemNamePointersJpn        0x004CD388  message_item_name_lookup 0x00491440
//   g_UnknownItemNamePointersJpn 0x004CD548  (= the last 16 name entries)
//   g_ItemDescriptionsJpn        0x004C9370  set_item_description_message 0x00491A40
//
// The readers pick these over the USA tables when the JPN asset tree is
// selected (config.ini [Assets] Version=JPN), because the encoding only means
// anything against data\\FONT.TIM.
//
// Item names end with 0x07, not 0x01: the message state machine reads that as
// "return from item name". STR_JP still appends its own 0x01 after it, exactly
// as STR() does for the USA names in MenuData.cpp; nothing reads past the 0x07.
#include "../Globals.h"
#include "PrintText.h"

''' % SELF

TEST_TOP = '''\
// test_str_jp.cpp - GENERATED by %s, do not edit by hand.
//
// Compile-time proof that STR_JP() reproduces the Japanese executable byte for
// byte. Every string in JpnTextTables.cpp is encoded from its readable source
// text and static_assert'd against the bytes read out of Biohazard.exe, so a
// wrong glyph table entry or a mis-parsed escape is a build error rather than
// garbled text on screen. Not part of the game build; compile it alone:
//
//   cl /nologo /c /EHsc tools\\test_str_jp.cpp
#include "../src/game/PrintText.h"

constexpr bool jp_same(const unsigned char* a, const unsigned char* b, int n)
{
    for (int i = 0; i < n; i++) {
        if (a[i] != b[i]) return false;
    }
    return true;
}

''' % SELF


def literal(text, tail=''):
    """Escape decoded text for a C++ u8"" literal.

    STR_JP reads its escapes from the literal's own characters, so every
    backslash has to survive C++ string-literal parsing: emit two.
    """
    return text.replace('\\', '\\\\').replace('"', '\\"') + tail


def comment(text, width=46):
    """One-line summary of a string for a trailing // comment."""
    c = text.replace('\\n', ' / ').replace('\\', '/')
    return c[:width]


def gen_header():
    m = build_map()
    rows = sorted((ord(ch), seq) for ch, seq in m.items() if len(ch) == 1)
    out = [HEADER_TOP]
    for cp, seq in rows:
        b0 = seq[0]
        b1 = seq[1] if len(seq) > 1 else 0
        n = len(seq)
        name = chr(cp)
        # A trailing backslash would splice the next table line into this
        # comment (MSVC C4010), silently dropping a glyph - 'a' in practice.
        if cp < 0x21 or cp == 0x7F or name == '\\':
            name = 'U+%04X' % cp
        out.append('    { 0x%04X, %d, 0x%02X, 0x%02X },  // %s\n' % (cp, n, b0, b1, name))
    out.append(HEADER_BOTTOM)
    return ''.join(out)


def read_tables():
    """Decode all four tables; returns {name: rows} plus a shared symbol map.

    Names and descriptions share strings heavily (79 descriptions are 40
    distinct strings), and the original tables point several entries at one
    string. Emitting one constant per unique address keeps that sharing instead
    of duplicating the bytes.
    """
    data = open(msg.EXE, 'rb').read()
    tables = {}
    for name, (va, n, term) in msg.TABLES.items():
        tables[name] = msg.table(data, va, n, term)
    return tables


def constants(rows, prefix, term):
    """Emit one constant per distinct string address, in address order."""
    seen = {}
    for i, p, text, dismiss, raw in rows:
        if text is None or p in seen:
            continue
        seen[p] = (text, dismiss, raw)
    out = []
    for p in sorted(seen):
        text, dismiss, raw = seen[p]
        tail = '\\\\x07' if term == 0x07 else ('\\\\d\\\\x%02X' % dismiss if dismiss else '')
        # Only annotate plain text; on the escape-heavy messages the comment
        # would just repeat the literal with the escapes mangled, and the
        # pointer table below already names every entry.
        note = '' if '\\' in text else '  // %s' % comment(text)
        out.append('static constexpr auto %s_%06X = STR_JP(u8"%s");%s\n'
                   % (prefix, p, literal(text, tail), note))
    return ''.join(out), seen


def pointer_table(rows, prefix, decl, count):
    out = ['%s = {\n' % decl]
    for i, p, text, dismiss, raw in rows:
        if text is None:
            out.append('    NULL,%s// [%3d] (out of bounds pointer)\n' % (' ' * 26, i))
        else:
            entry = '    (unsigned char*)%s_%06X.bytes,' % (prefix, p)
            out.append('%-46s// [%3d] %s\n' % (entry, i, comment(text)))
    for i in range(len(rows), count):
        out.append('    NULL,%s// [%3d]\n' % (' ' * 26, i))
    out.append('};\n\n')
    return ''.join(out)


SECTIONS = [
    # table key, symbol prefix, declaration, declared size, banner
    ('messages', 's_gmjp', 'unsigned char* global_messages_jpn[64]', 64,
     'global_messages_jpn (Biohazard.exe 0x004CDE58)'),
    ('names', 's_injp', 'extern const unsigned char* g_ItemNamePointersJpn[128]', 128,
     'g_ItemNamePointersJpn (0x004CD388), indexed by itemId - 1'),
    ('unknown', 's_injp',
     'extern const unsigned char* g_UnknownItemNamePointersJpn[16]', 16,
     'g_UnknownItemNamePointersJpn (0x004CD548) - shown for unexamined items'),
    ('descriptions', 's_idjp', 'unsigned char* g_ItemDescriptionsJpn[79]', 79,
     'g_ItemDescriptionsJpn (0x004C9370) - item viewer examine text'),
]


def gen_tables():
    t = read_tables()
    t['descriptions'] = t.pop('items')
    out = [CPP_TOP]
    emitted = set()
    for key, prefix, decl, count, banner in SECTIONS:
        rows = t[key]
        term = 0x07 if key in ('names', 'unknown') else 0x01
        text, seen = constants(rows, prefix, term)
        # 'unknown' is a slice of 'names' and its constants are already out.
        fresh = ''.join(line for line in text.splitlines(True)
                        if line.split('=')[0].strip() not in emitted)
        for line in text.splitlines():
            emitted.add(line.split('=')[0].strip())
        out.append('// %s\n' % ('-' * 74))
        out.append('// %s\n' % banner)
        out.append('// %s\n' % ('-' * 74))
        if fresh:
            out.append(fresh + '\n')
        out.append(pointer_table(rows, prefix, decl, count))
    return ''.join(out)


def gen_test():
    t = read_tables()
    t['descriptions'] = t.pop('items')
    out = [TEST_TOP]
    n = 0
    for key, prefix, decl, count, banner in SECTIONS:
        if key == 'unknown':
            continue                    # same strings as 'names'
        term = 0x07 if key == 'names' else 0x01
        seen = set()
        for i, p, text, dismiss, raw in t[key]:
            if text is None or p in seen:
                continue
            seen.add(p)
            tail = '\\\\x07' if term == 0x07 else \
                   ('\\\\d\\\\x%02X' % dismiss if dismiss else '')
            want = raw + (bytes([0x07, 0x01]) if term == 0x07
                          else bytes([0x01, dismiss]))
            hexed = ', '.join('0x%02X' % b for b in want)
            out.append('static constexpr auto t%03d = STR_JP(u8"%s");\n'
                       % (n, literal(text, tail)))
            out.append('static constexpr unsigned char e%03d[] = { %s };\n' % (n, hexed))
            out.append('static_assert(jp_same(t%03d.bytes, e%03d, sizeof(e%03d)),'
                       ' "%s[%d] 0x%08X");\n\n' % (n, n, n, key, i, p))
            n += 1
    out.append('int main() { return 0; }\n')
    return ''.join(out)


def write(path, text):
    full = os.path.join(ROOT, path)
    with open(full, 'w', encoding='utf-8-sig', newline='\r\n') as f:
        f.write(text)
    print('wrote %s (%d bytes)' % (path, len(text)))


def main():
    write('src/game/JpnFontTable.h', gen_header())
    write('src/game/JpnTextTables.cpp', gen_tables())
    write('tools/test_str_jp.cpp', gen_test())


if __name__ == '__main__':
    main()
